version: '2'
services:
  web:
    build: ./  
    image: brettt89/silverstripe-web:7.1-platform
    container_name: web
    working_dir: /var/www
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    volumes_from:
      - mysql
    links:
      - mysql
      - phpmyadmin
 
  mysql:
    image: mysql:5.6
    container_name: mysql
    hostname: localhost
    volumes:
      - /var/lib/mysql
      - ./shared:/shared
      - /usr/bin
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sampledb
      - MYSQL_USER=root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - '8090:80'
    links:
      - mysql:db